<?php
$title = 'edit population';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', 
        $this->url('population', array(
                'action' => 'edit',
                'id'     => $this->id,
        )));
$form->prepare();

echo $this->form()->openTag($form);

echo "<div class=\"form-group\">" . $this->formRow(
        $form->get('name')
            ->setAttribute('class', 'form-control')) . "</div>";

echo "<div class=\"form-group\">" . $this->formRow(
        $form->get('type')
        ->setAttribute('class', 'form-control')) . "</div>";

echo "<div class=\"form-group\">" . $this->formRow(
        $form->get('description')
            ->setAttribute('class', 'form-control'));

$form->get('submit')->setAttribute('value', 'save population');

echo "<div class=\"form-group\">" . $this->formRow(
        $form->get('submit')
        ->setAttribute('class', 'btn-primary')) . "</div>";

// echo $this->formCollection($form);
echo $this->form()->closeTag();
?>
