<?php
$title = 'About Treetype';
$this->headTitle($title);
?>

<div class="page-head">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2>About TreeType </h2>
        <h4>something goes here</h4>
      </div>
    </div>
  </div>
</div>

<br>
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<h4>TreeType - What is this?</h4>
			<p>The phenotype is the complete set of observable traits of an
				organism; a product of the genotype interacting with the
				environment. As technology is rapidly delivering ever-better
				understanding of the genotype, more knowledge of the phenotype is
				imperative. Treetype aims to fill that gap for trees in wild
				populations, collecting data on individual trees and their
				environments. Treetype is an open project and welcomes contributions
				from anyone willing to dedicate a little time to recording data -
				from single trees or whole forests as your resources allow. If there
				is a species for which you want to see a data collection, our voting
				tool allows nomination of new species for the database - once enough
				recorders show an interest in recording for a nominated species, we
				will organise the start of a new collection.</p>
			<p>
				<strong>Every tree is important!</strong>
			</p>
		</div>
		<div class="col-md-6">
			<div class="bthumb">
				<a href="#"><img
					src="<?php echo $this->basePath('img/photos/PICT1210.JPG')?>"
					alt="" class="img-responsive" /></a>
			</div>
		</div>

	</div>
</div>
